export type GenerationType = "Lesson Notes" | "Topic Summary" | "Practice Problem Set";

export function generateTeachingContent(type: GenerationType, topic: string, courseTitle: string): { title: string; summary: string; pages: number } {
  switch (type) {
    case "Lesson Notes":
      return {
        title: `${topic} — Lesson Notes.pdf`,
        summary: `Structured lesson notes for ${topic} in ${courseTitle}: learning objectives, key definitions, a worked example, and 3 discussion questions for class. Generated by ATDT from your course materials — review before publishing.`,
        pages: 8,
      };
    case "Topic Summary":
      return {
        title: `${topic} — Summary Sheet.pdf`,
        summary: `One-page summary of ${topic} covering the core concept, the most common mistake students make, and a one-line takeaway for quick revision before exams.`,
        pages: 1,
      };
    case "Practice Problem Set":
      return {
        title: `${topic} — Practice Problems.pdf`,
        summary: `Auto-generated problem set on ${topic} with 6 graduated-difficulty questions and an answer key, drawn from the same patterns as your published assessment questions.`,
        pages: 4,
      };
  }
}
