import { useState } from "react";
import { BookOpen, Users, FileText, AlertTriangle, Sparkles, ExternalLink } from "lucide-react";
import { documents, students, teacher } from "../data/mockData";
import { useAppState } from "../state/AppState";
import { generateTeachingContent, type GenerationType } from "../lib/generate";
import { makePdfBlobUrl } from "../lib/pdf";

function GenerateWithAtdt() {
  const { currentCourse, addDocument } = useAppState();
  const [type, setType] = useState<GenerationType>("Lesson Notes");
  const [topic, setTopic] = useState(currentCourse.topics[0]?.topic ?? "");
  const [draft, setDraft] = useState<{ title: string; summary: string; pages: number } | null>(null);
  const [saved, setSaved] = useState(false);

  const generate = () => {
    setDraft(generateTeachingContent(type, topic, currentCourse.title));
    setSaved(false);
  };

  const saveToLibrary = () => {
    if (!draft) return;
    addDocument({
      title: draft.title,
      courseId: currentCourse.id,
      module: "ATDT Generated",
      topic,
      pages: draft.pages,
      sizeKb: draft.pages * 60,
      uploadedBy: `${teacher.name} (via ATDT)`,
      summary: draft.summary,
    });
    setSaved(true);
  };

  const preview = () => {
    if (!draft) return;
    const url = makePdfBlobUrl(draft.title.replace(/\.pdf$/i, ""), `${type} · ${topic} · Generated by ATDT`, [draft.summary]);
    window.open(url, "_blank");
  };

  return (
    <div className="card card-pad">
      <div className="h2">
        <Sparkles size={16} color="var(--coral)" /> Generate with ATDT
      </div>
      <p className="muted" style={{ marginBottom: 12 }}>
        Draft lesson notes, summaries, or practice sets from your course material — review before publishing to the Library.
      </p>
      <div style={{ display: "flex", gap: 10, marginBottom: 12, flexWrap: "wrap" }}>
        <select value={type} onChange={(e) => setType(e.target.value as GenerationType)} style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid var(--border)", fontSize: 13 }}>
          <option>Lesson Notes</option>
          <option>Topic Summary</option>
          <option>Practice Problem Set</option>
        </select>
        <select value={topic} onChange={(e) => setTopic(e.target.value)} style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid var(--border)", fontSize: 13 }}>
          {currentCourse.topics.map((t) => (
            <option key={t.topic} value={t.topic}>
              {t.topic}
            </option>
          ))}
        </select>
        <button className="btn btn-navy" onClick={generate}>
          Generate
        </button>
      </div>

      {draft && (
        <div style={{ background: "var(--bg)", borderRadius: 10, padding: 14 }}>
          <div style={{ fontWeight: 700, color: "var(--navy)", marginBottom: 6 }}>{draft.title}</div>
          <p style={{ fontSize: 13, color: "var(--text)", lineHeight: 1.5, marginBottom: 12 }}>{draft.summary}</p>
          <div style={{ display: "flex", gap: 8 }}>
            <button className="btn btn-outline" onClick={preview}>
              <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
                <ExternalLink size={13} /> Preview PDF
              </span>
            </button>
            <button className="btn btn-primary" onClick={saveToLibrary} disabled={saved}>
              {saved ? "Saved to Library ✓" : "Save to Library"}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export function TeacherOverview() {
  const { currentCourse } = useAppState();
  const roster = students.filter((s) => s.courseId === currentCourse.id);
  const courseDocs = documents.filter((d) => d.courseId === currentCourse.id);
  const atRisk = roster.filter((s) => s.topics.some((t) => t.status === "struggling"));

  return (
    <div className="main-content">
      <div className="page-scroll stack">
        <div>
          <h1 className="h1">Welcome back, {teacher.name.split(" ")[1] ?? teacher.name}</h1>
          <p className="muted">{currentCourse.title} — Teaching Twin overview.</p>
        </div>

        <div className="grid-3">
          <div className="card card-pad">
            <Users size={22} color="var(--navy)" style={{ marginBottom: 8 }} />
            <div className="muted">Students enrolled</div>
            <div style={{ fontSize: 24, fontWeight: 800, color: "var(--navy)" }}>{roster.length}</div>
          </div>
          <div className="card card-pad">
            <FileText size={22} color="var(--coral)" style={{ marginBottom: 8 }} />
            <div className="muted">Materials uploaded</div>
            <div style={{ fontSize: 24, fontWeight: 800, color: "var(--navy)" }}>{courseDocs.length}</div>
          </div>
          <div className="card card-pad">
            <AlertTriangle size={22} color="var(--red)" style={{ marginBottom: 8 }} />
            <div className="muted">Students at risk</div>
            <div style={{ fontSize: 24, fontWeight: 800, color: "var(--navy)" }}>{atRisk.length}</div>
          </div>
        </div>

        <div className="card card-pad">
          <div className="h2">
            <BookOpen size={16} /> Teaching Twin status
          </div>
          <p style={{ fontSize: 13, color: "var(--text)", lineHeight: 1.6 }}>
            ATDT has ingested <strong>{courseDocs.length} documents</strong> and is tutoring students using your
            uploaded material for {currentCourse.title}. Open your <strong>Teaching Twin &amp; Roster</strong> panel
            (brain icon in the sidebar) to inspect any student's cognitive profile directly.
          </p>
        </div>

        <GenerateWithAtdt />

        <div className="card card-pad">
          <div className="h2">Students needing attention</div>
          {atRisk.length === 0 && <p className="muted">Nobody is currently flagged as struggling. 🎉</p>}
          {atRisk.map((s) => {
            const weakest = [...s.topics].sort((a, b) => a.mastery - b.mastery)[0];
            return (
              <div key={s.id} className="row-between" style={{ padding: "10px 0", borderTop: "1px solid var(--border)" }}>
                <span style={{ fontWeight: 600, fontSize: 13, color: "var(--navy)" }}>{s.name}</span>
                <span className="muted">
                  Weakest: {weakest.topic} ({weakest.mastery}%)
                </span>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
